<a href="https://colab.research.google.com/github/aso1801031/AI_teach2020/blob/master/20201009AI0208_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ## sklearnでエラーが出るので、前のバージョンを入れ直す

In [2]:
# 現在のscikitーlearnをcolabのVMからアンインストール
!pip uninstall scikit-learn
# 前のバージョンを指定してvmにいんすとーる
!pip install scikit-learn==0.20 --ignore-installed

Uninstalling scikit-learn-0.22.2.post1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/scikit_learn-0.22.2.post1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.22.2.post1
     |████████████████████████████████| 5.3MB 2.6MB/s 
     |████████████████████████████████| 14.9MB 300kB/s 
     |████████████████████████████████| 25.9MB 168kB/s 
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.3 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement scipy==1.4.1, but you'll have scipy 1.5.3 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.


### all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [3]:
# ライブラリ読み込み
import pandas as pd
# 学習用データとテスト検証用データを分割する
from sklearn.model_selection import train_test_split
# 正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimaios(推定機の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings

### Webからあやめのデータを読み込む

In [4]:
# urリンクから読み込むライブラリ
import urllib.request as req
# url用の文字列変数を定義
url ="https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
#リンクから保存するためのファイル名を定義
savefile = "iris.csv"
# requestクラスを使ってurlからデータをsavefileへコピーして保存
req.urlretrieve(url,savefile)
#pandasのreadメソッドを使ってcsvファイルを読み込む
iris_data = pd.read_csv(savefile,encoding="utf-8")
iris_data.head()


SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### アヤメデータを目的変数yと説明変数xに分離する

In [5]:
y = iris_data.loc[:, "Name"] #目的変数
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]] #説明変数

print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


### アヤメデータをさらに学習用とテストように分離する

In [6]:
# 学習用データ（train）と検証用データ（test）に分離
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8,shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
102          7.1         3.0          5.9         2.1
130          7.4         2.8          6.1         1.9
21           5.1         3.7          1.5         0.4
84           5.4         3.0          4.5         1.5
50           7.0         3.2          4.7         1.4
102     Iris-virginica
130     Iris-virginica
21         Iris-setosa
84     Iris-versicolor
50     Iris-versicolor
Name: Name, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth
52           6.9         3.1          4.9         1.5
78           6.0         2.9          4.5         1.5
62           6.0         2.2          4.0         1.0
14           5.8         4.0          1.2         0.2
115          6.4         3.2          5.3         2.3
52     Iris-versicolor
78     Iris-versicolor
62     Iris-versicolor
14         Iris-setosa
115     Iris-virginica
Name: Name, dtype: object


### allAlgorithmsにclassifierを指定して「分類」でフィルターしたアルゴリズムの推定器群を取得する

In [7]:
# 推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings("ignore")

### 推定器のリストをループしながら学習&推論させる

In [8]:
#推定器のリストをループ
for(name,algorithm) in allAlgorithms:
  #各アルゴリズムのオブジェクトを生成
  clf = algorithm() # 各アルゴリズムクラスのコンストラクトを実行
  #　学習させる
  clf.fit(x_train,y_train)
  # 推論する
  y_pred = clf.predict(x_test)
  # accuracy_scoreで正解率を算出して表示
  print(name,"正解率 = ",accuracy_score(y_test,y_pred) )

AdaBoostClassifier 正解率 =  1.0
BaggingClassifier 正解率 =  1.0
BernoulliNB 正解率 =  0.3
CalibratedClassifierCV 正解率 =  0.9666666666666667
ComplementNB 正解率 =  0.7
DecisionTreeClassifier 正解率 =  0.9666666666666667
ExtraTreeClassifier 正解率 =  1.0
ExtraTreesClassifier 正解率 =  0.9666666666666667
GaussianNB 正解率 =  0.9666666666666667
GaussianProcessClassifier 正解率 =  0.9666666666666667
GradientBoostingClassifier 正解率 =  1.0
KNeighborsClassifier 正解率 =  1.0
LabelPropagation 正解率 =  1.0
LabelSpreading 正解率 =  1.0
LinearDiscriminantAnalysis 正解率 =  1.0
LinearSVC 正解率 =  1.0
LogisticRegression 正解率 =  1.0
LogisticRegressionCV 正解率 =  1.0
MLPClassifier 正解率 =  1.0
MultinomialNB 正解率 =  0.9666666666666667
NearestCentroid 正解率 =  0.9
NuSVC 正解率 =  0.9666666666666667
PassiveAggressiveClassifier 正解率 =  0.8666666666666667
Perceptron 正解率 =  0.7
QuadraticDiscriminantAnalysis 正解率 =  1.0
RadiusNeighborsClassifier 正解率 =  0.9666666666666667
RandomForestClassifier 正解率 =  1.0
RidgeClassifier 正解率 =  0.9
RidgeClassifierCV 正解率 =  0.9
S

## クロスバリデーション 

### クロスバリデーション 関連のライブラリのインポート

In [9]:
# ライブラリのインポート
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

### クロスバリデーション を実行する

In [10]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
# 　すでに生成してあるall_astimatorsのインスタンスをループさせて、クロスバリデーション を行う
for(name,algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    #scoreの属性がある学習モデルだけに送る
    if hasattr(clf,"score"):
      scores = cross_val_score(clf,x,y,cv=kfold_cv)
      #k=n splits=5回分のクロスバリデーション のスコアを表示
      print(name,"の正解率=")
      print(scores)
      #ifブロック終了
    #tryブロック終了
  except : #例外処理のブロック
  #except Exception e:
  #print(e)
    #何もしない
    pass


AdaBoostClassifier の正解率=
[0.96666667 0.96666667 0.93333333 0.9        0.93333333]
BaggingClassifier の正解率=
[1.         0.93333333 0.96666667 0.96666667 0.93333333]
BernoulliNB の正解率=
[0.26666667 0.33333333 0.26666667 0.3        0.2       ]
CalibratedClassifierCV の正解率=
[0.9        0.9        0.93333333 0.86666667 1.        ]
ComplementNB の正解率=
[0.7        0.6        0.7        0.7        0.63333333]
DecisionTreeClassifier の正解率=
[0.96666667 0.96666667 0.9        0.86666667 1.        ]
ExtraTreeClassifier の正解率=
[0.9        0.9        0.96666667 0.96666667 0.86666667]
ExtraTreesClassifier の正解率=
[0.96666667 0.93333333 0.9        0.93333333 0.96666667]
GaussianNB の正解率=
[0.96666667 0.96666667 1.         0.93333333 0.9       ]
GaussianProcessClassifier の正解率=
[0.9        1.         0.96666667 0.93333333 0.96666667]
GradientBoostingClassifier の正解率=
[0.96666667 0.93333333 0.86666667 1.         0.96666667]
KNeighborsClassifier の正解率=
[0.96666667 0.96666667 0.96666667 0.96666667 0.96666667]
LabelPropa

### おまけ: もっと詳しい結果を取得できるクロスバリデーション オブジェクト:cross_validate

In [11]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

### cross_validateを使ったクロスバリデーション 

In [12]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
# 　すでに生成してあるall_astimatorsのインスタンスをループさせて、クロスバリデーション を行う
for(name,algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    #scoreの属性がある学習モデルだけに送る
    if hasattr(clf,"score"):
      scores = cross_validate(clf,x,y,cv=kfold_cv)
      #k=n splits=5回分のクロスバリデーション のスコアを表示
      print(name,"の正解率=")
      print(scores)
      #ifブロック終了
    #tryブロック終了
  except : #例外処理のブロック
    #何もしない
    pass

AdaBoostClassifier の正解率=
{'fit_time': array([0.06827021, 0.06305838, 0.06095505, 0.06067491, 0.0629313 ]), 'score_time': array([0.00579906, 0.00568843, 0.00660396, 0.0065608 , 0.00571918]), 'test_score': array([0.93333333, 0.93333333, 0.93333333, 0.8       , 1.        ]), 'train_score': array([0.96666667, 0.95      , 0.96666667, 0.98333333, 0.95      ])}
BaggingClassifier の正解率=
{'fit_time': array([0.01438928, 0.01327825, 0.01315498, 0.01310158, 0.01296353]), 'score_time': array([0.00175285, 0.00185919, 0.00171685, 0.00172305, 0.00170135]), 'test_score': array([0.96666667, 0.9       , 0.9       , 1.        , 0.96666667]), 'train_score': array([1.        , 0.99166667, 1.        , 1.        , 0.99166667])}
BernoulliNB の正解率=
{'fit_time': array([0.00307441, 0.00180054, 0.00178075, 0.0018599 , 0.00175261]), 'score_time': array([0.0009141 , 0.00081253, 0.00081563, 0.00087023, 0.00079346]), 'test_score': array([0.3       , 0.23333333, 0.2       , 0.26666667, 0.3       ]), 'train_score': array(

## グリッドサーチで最適なパラメータを探し求める

### ライブラリをimport

In [13]:
# グリッドサーチ
from sklearn.model_selection import GridSearchCV
# SVCアルゴリズムの学習モデルをimport
from sklearn.svm import SVC

### グリッドサーチを実行してパラメータを試す

In [14]:
# グリッドサーチを試すパラメ０他のパターンを指定する
parameters = [
              #３つのパラメータ、3パターン
              {"C":[1,10,100,1000],"kernel":["linear"]},
              {"C":[1,10,100,1000],"kernel":["rbf"],"gamma":[0.001,0.0001]},
              {"C":[1,10,100,1000],"kernel":["sigmoid"],"gamma":[0.001,0.0001]}
              ]

# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
#普通の学習
clf = SVC()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率 = ",accuracy_score(y_test,y_pred))

#  グリッドサーチを行う
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
# グリッドサーチの中でK分割交差検証も行われる
clf_grid = GridSearchCV(SVC(),parameters,cv=kfold_cv) # インスタンス
clf_grid.fit(x_train,y_train) #学習
# 学習済みのもでるに最終的に設定された(最適と思われる)パラメータを表示
print("最適なパラメータ = ",clf_grid.best_estimator_)

#　最適なパラメータを表示
y_pred = clf_grid.predict(x_test)
print("グリッドサーチの正解率=",accuracy_score(y_pred,y_test))

普通の学習の正解率 =  1.0
最適なパラメータ =  SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
グリッドサーチの正解率= 1.0


### Numpyの動作確認

In [15]:
import numpy as np

In [16]:
# numpy配列の初期化
a = np.array([1,2,3,4,5]) # ndarrayという配列オブジェクトを生成
print(a)
#型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# ２次元のndarrayを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [18]:
# 配列の要素数を指定して0で初期化
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [19]:
# 連番の配列を要素数を指定して初期化
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


### numpyで行列計算

In [20]:
# numpyで行列計算
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
print(x)
y = 3*x + 5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [29]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [26]:
# Numpy配列で次元数を変換する
a = np.array([[1,2,3],[4,5,6]])
print("a=", a)
b = a.flatten()
print("b=", b)

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### numpyの配列にアクセスする方法

In [27]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a) # 二次元配列の０行目
b = v[1:] #  一列目いこう
print(b)
c = v[:,0]
print(c)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
